name: target build

on:
  workflow_call:
    inputs:
      targets:
        description: 'stringified array of target browsers'
        default: '["chrome", "safari"]'
        required: false
        type: string

jobs:
  build-chrome:
    name: build chrome
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        target: ${{fromJson(inputs.targets)}}
    steps:
      - name: all okay for chrome?
        if: matrix.target == 'chrome'
        run: echo "ok for chrome"
      - name: all okay for safari?
        if: matrix.target == 'safari'
        run: echo "ok for safari"
