name: target build

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: choice
        description: choose target browser to build the extension for
        options:
        - chrome
        - safari

jobs:
  build-chrome:
    name: build chrome
    runs-on: 'ubuntu-latest'
    if: inputs.target == 'chrome'
    steps:
      - name: all okay for chrome?
        run: echo "ok for chrome"
  build-safari:
    name: build safari
    runs-on: 'macos-11'
    if: inputs.target == 'safari'
    steps:
      - name: all okay for safari?
        if: inputs.target == 'safari'
        run: echo "ok for safari"
