name: parallel builds

on:
  - pull_request
  - push

jobs:
  build:
    name: build
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        target: [chrome, safari]
    steps:
      - name: build chrome
        if: matrix.target == 'chrome'
        uses: paambaati/gh-actions-tests/.github/workflows/chrome.yml@main
      - name: build safari
        if: matrix.target == 'safari'
        uses: paambaati/gh-actions-tests/.github/workflows/safari.yml@main

  finish:
    name: final step
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: all okay?
        run: echo "ok"
