name: parallel builds

on:
  - pull_request
  - push

jobs:
  build:
    name: build
    uses: paambaati/gh-actions-tests/.github/workflows/browser-build.yml@main
    with:
      targets: >-
        ["chrome", "safari"]

  finish:
    name: final step
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: all okay?
        run: echo "ok"
