name: parallel builds

on:
  - pull_request
  - push

jobs:
  build:
    name: build
    strategy:
      matrix:
        target: [chrome, safari]
    uses: paambaati/gh-actions-tests/.github/workflows/browser-build.yml@main
    with:
      target: ${{ matrix.target}}

  finish:
    name: final step
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: all okay?
        run: echo "ok"
